spring.application.name=demo
logging.level.org.springframework.web=DEBUG
spring.application.name=Etudiant Management System
spring.datasource.url=jdbc:postgresql://localhost:5432/etudiant_sys
spring.datasource.username=postgres
spring.datasource.password=sql123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hisbernate.format_sql=true

spring.main.allow-circular-references=true
jwt.secret=d2e85a98284ad65f2dd3d847ea58a5e9490e5ee697dbb328c2b1ea7f5eefd6db
#Cette propriété dit à Hibernate quoi faire avec le schéma de la base de données au démarrage de l'application
#on la transforme en "create" a chaque fois on create un nouveau table dans ddb
spring.jpa.hibernate.ddl-auto=none
# Configuration du serveur
server.port=8080

#configuration de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hajibshaymaa@gmail.com
spring.mail.password=vbcrobnhlbenhjee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

backend.origin=http://localhost:8080

spring.mail.properties.mail.debug=true